import os
import subprocess
import glob

WORKSPACE = "/Users/aryanmaurya/numerical analysis. "
BUILD_DIR = os.path.join(WORKSPACE, "pdf_build")
OUTPUT_PDF = os.path.join(WORKSPACE, "Numerical_Computing_Python_Handbook.pdf")

METADATA = [
    # Unit 1: Roots of Equations
    {
        "id": "01",
        "title": "Bisection Method",
        "category": "Roots of Non-Linear Equations",
        "chapter": "Transcendental \\& Polynomial Equations",
        "detailed_file": "01_bisection_detailed.py",
        "desc": "The Bisection method is a robust bracketing method for finding real roots of a continuous function $f(x) = 0$. Given an initial bracket $[a, b]$ where $f(a) \\cdot f(b) < 0$, Bolzano's theorem guarantees at least one root in $(a, b)$. In each iteration, the midpoint $c$ is calculated and the sign of $f(c)$ determines which sub-interval is retained.",
        "formula": r"""\[
c = \frac{a + b}{2.0}, \quad \text{Update: } b = c \text{ if } f(a) \cdot f(c) < 0, \quad a = c \text{ if } f(a) \cdot f(c) > 0
\]
\[
\text{Convergence: Linear}, \quad |e_{n+1}| \le \frac{1}{2}|e_n|, \quad \text{Error Bound: } \frac{b - a}{2^n}
\]"""
    },
    {
        "id": "02",
        "title": "Regula-Falsi (False Position) Method",
        "category": "Roots of Non-Linear Equations",
        "chapter": "Transcendental \\& Polynomial Equations",
        "detailed_file": "02_regula_falsi_detailed.py",
        "desc": "The Regula-Falsi (False Position) method combines the reliability of bracketing with the acceleration of linear interpolation. Instead of bisecting the interval geometrically, it connects $(a, f(a))$ and $(b, f(b))$ with a secant line and determines the root estimate $c$ at the line's $x$-intercept.",
        "formula": r"""\[
c = \frac{a f(b) - b f(a)}{f(b) - f(a)} = a - \frac{f(a)(b - a)}{f(b) - f(a)}
\]
\[
\text{Update: } b = c \text{ if } f(a) \cdot f(c) < 0, \quad a = c \text{ if } f(a) \cdot f(c) > 0
\]"""
    },
    {
        "id": "03",
        "title": "Newton-Raphson Method",
        "category": "Roots of Non-Linear Equations",
        "chapter": "Transcendental \\& Polynomial Equations",
        "detailed_file": "03_newton_raphson_detailed.py",
        "desc": "The Newton-Raphson method is an open root-finding technique that utilizes the tangent line at the current estimate $x_k$. Starting from an initial guess $x_0$, the method converges with quadratic order near simple roots.",
        "formula": r"""\[
x_{k+1} = x_k - \frac{f(x_k)}{f'(x_k)}
\]
\[
\text{Order of Convergence: } p = 2 \quad (\text{Quadratic, requires } f'(x_k) \neq 0)
\]"""
    },
    {
        "id": "04",
        "title": "Secant Method",
        "category": "Roots of Non-Linear Equations",
        "chapter": "Transcendental \\& Polynomial Equations",
        "detailed_file": "04_secant_detailed.py",
        "desc": "The Secant method approximates the analytical derivative in Newton-Raphson using a finite-difference slope between the two most recent estimates $x_{k-1}$ and $x_k$. This avoids calculating $f'(x)$ while retaining rapid superlinear convergence.",
        "formula": r"""\[
x_{k+1} = x_k - f(x_k) \cdot \frac{x_k - x_{k-1}}{f(x_k) - f(x_{k-1})}
\]
\[
\text{Order of Convergence: } p = \frac{1 + \sqrt{5}}{2} \approx 1.618 \quad (\text{Golden Ratio, Superlinear})
\]"""
    },
    {
        "id": "05",
        "title": "Fixed-Point Iteration Method",
        "category": "Roots of Non-Linear Equations",
        "chapter": "Transcendental \\& Polynomial Equations",
        "detailed_file": "05_fixed_point_detailed.py",
        "desc": "Fixed-point iteration rewrites the root problem $f(x) = 0$ as $x = g(x)$. Starting from $x_0$, successive estimates are generated by repeatedly evaluating $g(x)$. Convergence is guaranteed if $|g'(x)| < 1$ in an interval containing the fixed point.",
        "formula": r"""\[
x_{k+1} = g(x_k)
\]
\[
\text{Convergence Condition: } |g'(x^*)| < 1 \quad (\text{Contraction Mapping})
\]"""
    },
    # Unit 2: Linear Systems
    {
        "id": "06",
        "title": "Gauss Elimination Method",
        "category": "Systems of Linear Algebraic Equations",
        "chapter": "Systems of Linear Algebraic Equations",
        "detailed_file": "06_gauss_elimination_detailed.py",
        "desc": "Gauss Elimination is a direct method for solving a system of linear equations $A x = b$. It transforms the augmented matrix $[A \\mid b]$ into upper-triangular form through forward row operations, followed by backward substitution to determine the unknowns.",
        "formula": r"""\[
\text{Forward Elimination: } m_{ik} = \frac{a_{ik}}{a_{kk}}, \quad R_i \leftarrow R_i - m_{ik} R_k \quad (i > k)
\]
\[
\text{Back Substitution: } x_i = \frac{1}{a_{ii}}\left(b_i - \sum_{j=i+1}^n a_{ij} x_j\right)
\]"""
    },
    {
        "id": "07",
        "title": "Gauss-Jordan Elimination Method",
        "category": "Systems of Linear Algebraic Equations",
        "chapter": "Systems of Linear Algebraic Equations",
        "detailed_file": "07_gauss_jordan_detailed.py",
        "desc": "Gauss-Jordan elimination reduces the coefficient matrix directly into reduced row echelon form (identity matrix $I$) by performing row eliminations both below and above each pivot element. The solution appears directly in the augmented column.",
        "formula": r"""\[
\text{Normalize Pivot Row: } R_i \leftarrow \frac{R_i}{a_{ii}}
\]
\[
\text{Eliminate Other Rows: } R_k \leftarrow R_k - a_{ki} R_i \quad (\forall k \neq i)
\]
\[
\text{Result: } [A \mid b] \longrightarrow [I \mid x]
\]"""
    },
    {
        "id": "08",
        "title": "Gauss-Jacobi Iterative Method",
        "category": "Systems of Linear Algebraic Equations",
        "chapter": "Systems of Linear Algebraic Equations",
        "detailed_file": "08_gauss_jacobi_detailed.py",
        "desc": "The Jacobi method is an iterative technique for solving $A x = b$. In each step, each unknown $x_i$ is updated solely using the values from the previous iteration step $k$. It converges for strictly diagonally dominant matrices.",
        "formula": r"""\[
x_i^{(k+1)} = \frac{1}{a_{ii}}\left(b_i - \sum_{j \neq i} a_{ij} x_j^{(k)}\right) \quad (i = 1, 2, \dots, n)
\]
\[
\text{Strict Diagonal Dominance: } |a_{ii}| > \sum_{j \neq i} |a_{ij}|
\]"""
    },
    {
        "id": "09",
        "title": "Gauss-Seidel Iterative Method",
        "category": "Systems of Linear Algebraic Equations",
        "chapter": "Systems of Linear Algebraic Equations",
        "detailed_file": "09_gauss_seidel_detailed.py",
        "desc": "The Gauss-Seidel method accelerates Jacobi iteration by immediately utilizing the newly updated components $x_1^{(k+1)}, \\dots, x_{i-1}^{(k+1)}$ as soon as they become available during the current iteration step.",
        "formula": r"""\[
x_i^{(k+1)} = \frac{1}{a_{ii}}\left(b_i - \sum_{j < i} a_{ij} x_j^{(k+1)} - \sum_{j > i} a_{ij} x_j^{(k)}\right)
\]
\[
\text{Convergence Rate: Typically converges in roughly half the iterations of Jacobi.}
\]"""
    },
    # Unit 3: Interpolation
    {
        "id": "10",
        "title": "Lagrange Interpolation",
        "category": "Interpolation \\& Polynomial Approximation",
        "chapter": "Interpolation \\& Polynomial Approximation",
        "detailed_file": "10_lagrange_detailed.py",
        "desc": "Lagrange interpolation constructs the unique polynomial of degree at most $n$ that passes through $n+1$ given points $(x_i, y_i)$. The formulation does not require the data nodes to be evenly spaced.",
        "formula": r"""\[
P_n(x) = \sum_{i=0}^n y_i \ell_i(x), \quad \text{where } \ell_i(x) = \prod_{\substack{j=0 \\ j \neq i}}^n \frac{x - x_j}{x_i - x_j}
\]"""
    },
    {
        "id": "11",
        "title": "Newton's Divided Difference Interpolation",
        "category": "Interpolation \\& Polynomial Approximation",
        "chapter": "Interpolation \\& Polynomial Approximation",
        "detailed_file": "11_newton_divided_diff_detailed.py",
        "desc": "Newton's Divided Difference method constructs an interpolating polynomial using divided differences. It is versatile for unequally spaced data points and allows easy addition of new data points without recomputing the entire table.",
        "formula": r"""\[
f[x_i, \dots, x_{i+k}] = \frac{f[x_{i+1}, \dots, x_{i+k}] - f[x_i, \dots, x_{i+k-1}]}{x_{i+k} - x_i}
\]
\[
P_n(x) = f[x_0] + \sum_{k=1}^n f[x_0, \dots, x_k] \prod_{j=0}^{k-1} (x - x_j)
\]"""
    },
    {
        "id": "12",
        "title": "Newton's Forward Difference Interpolation",
        "category": "Interpolation \\& Polynomial Approximation",
        "chapter": "Interpolation \\& Polynomial Approximation",
        "detailed_file": "12_newton_forward_detailed.py",
        "desc": "Newton's Forward Difference formula is designed for tabulated data where nodes are equally spaced ($x_i = x_0 + i h$). It is ideal for interpolating values near the start of the table.",
        "formula": r"""\[
u = \frac{x - x_0}{h}, \quad \Delta y_i = y_{i+1} - y_i
\]
\[
P_n(x) = y_0 + u \Delta y_0 + \frac{u(u-1)}{2!} \Delta^2 y_0 + \dots + \frac{u(u-1)\dots(u-n+1)}{n!} \Delta^n y_0
\]"""
    },
    # Unit 4: Integration
    {
        "id": "13",
        "title": "Trapezoidal Rule of Numerical Integration",
        "category": "Numerical Quadrature \\& Integration",
        "chapter": "Numerical Quadrature \\& Integration",
        "detailed_file": "13_trapezoidal_detailed.py",
        "desc": "The composite Trapezoidal rule evaluates $\\int_a^b f(x)\\,dx$ by approximating the integrand with linear segments across $n$ uniform subintervals of width $h = \\frac{b-a}{n}$.",
        "formula": r"""\[
I \approx \frac{h}{2}\left[f(a) + 2 \sum_{i=1}^{n-1} f(x_i) + f(b)\right], \quad h = \frac{b - a}{n}
\]
\[
\text{Global Truncation Error: } E_T = -\frac{(b - a) h^2}{12} f''(\xi) \quad (\mathcal{O}(h^2) \text{ Accuracy})
\]"""
    },
    {
        "id": "14",
        "title": "Simpson's 1/3 Rule of Numerical Integration",
        "category": "Numerical Quadrature \\& Integration",
        "chapter": "Numerical Quadrature \\& Integration",
        "detailed_file": "14_simpson_1_3_detailed.py",
        "desc": "Simpson's 1/3 rule fits quadratic parabolas over adjacent pairs of subintervals. The total number of intervals $n$ must be an even integer. It achieves fourth-order accuracy.",
        "formula": r"""\[
I \approx \frac{h}{3}\left[f(a) + f(b) + 4 \sum_{i \text{ odd}} f(x_i) + 2 \sum_{i \text{ even}} f(x_i)\right], \quad (n \text{ must be even})
\]
\[
\text{Global Truncation Error: } E_S = -\frac{(b - a) h^4}{180} f^{(4)}(\xi) \quad (\mathcal{O}(h^4) \text{ Accuracy})
\]"""
    },
    {
        "id": "15",
        "title": "Simpson's 3/8 Rule of Numerical Integration",
        "category": "Numerical Quadrature \\& Integration",
        "chapter": "Numerical Quadrature \\& Integration",
        "detailed_file": "15_simpson_3_8_detailed.py",
        "desc": "Simpson's 3/8 rule fits cubic polynomials across groups of three consecutive subintervals. The total number of subintervals $n$ must be a multiple of 3.",
        "formula": r"""\[
I \approx \frac{3h}{8}\left[f(a) + f(b) + 3 \sum_{i \nmid 3} f(x_i) + 2 \sum_{i \mid 3} f(x_i)\right], \quad (n \in 3\mathbb{Z})
\]
\[
\text{Global Truncation Error: } E_{3/8} = -\frac{(b - a) h^4}{80} f^{(4)}(\xi) \quad (\mathcal{O}(h^4) \text{ Accuracy})
\]"""
    },
    # Unit 5: Differential Equations
    {
        "id": "16",
        "title": "Euler's Method for ODEs",
        "category": "Ordinary Differential Equations (ODEs)",
        "chapter": "Ordinary Differential Equations (ODEs)",
        "detailed_file": "16_euler_detailed.py",
        "desc": "Euler's method is the classical first-order explicit single-step method for solving initial value problems $\\frac{dy}{dx} = f(x, y)$ with $y(x_0) = y_0$.",
        "formula": r"""\[
y_{n+1} = y_n + h \cdot f(x_n, y_n)
\]
\[
\text{Global Error Order: } \mathcal{O}(h) \quad (\text{First-Order Accurate})
\]"""
    },
    {
        "id": "17",
        "title": "Modified Euler's (Heun's) Method",
        "category": "Ordinary Differential Equations (ODEs)",
        "chapter": "Ordinary Differential Equations (ODEs)",
        "detailed_file": "17_modified_euler_detailed.py",
        "desc": "Heun's (Modified Euler) method improves upon Euler's method by implementing a predictor-corrector scheme that averages slopes at both the start and predicted end of the step.",
        "formula": r"""\[
\text{Predictor: } \tilde{y}_{n+1} = y_n + h \cdot f(x_n, y_n)
\]
\[
\text{Corrector: } y_{n+1} = y_n + \frac{h}{2}\left[f(x_n, y_n) + f(x_{n+1}, \tilde{y}_{n+1})\right] \quad (\mathcal{O}(h^2) \text{ Accuracy})
\]"""
    },
    {
        "id": "18",
        "title": "Runge-Kutta 4th Order Method (RK4)",
        "category": "Ordinary Differential Equations (ODEs)",
        "chapter": "Ordinary Differential Equations (ODEs)",
        "detailed_file": "18_rk4_detailed.py",
        "desc": "The classical Runge-Kutta 4th Order (RK4) method evaluates four intermediate slopes per step and combines them with Simpson-type weighting to achieve fourth-order accuracy without evaluating higher derivatives.",
        "formula": r"""\[
k_1 = h f(x_n, y_n), \quad k_2 = h f\left(x_n + \frac{h}{2}, y_n + \frac{k_1}{2}\right)
\]
\[
k_3 = h f\left(x_n + \frac{h}{2}, y_n + \frac{k_2}{2}\right), \quad k_4 = h f(x_n + h, y_n + k_3)
\]
\[
y_{n+1} = y_n + \frac{1}{6}(k_1 + 2k_2 + 2k_3 + k_4) \quad (\mathcal{O}(h^4) \text{ Accuracy})
\]"""
    },
    # Unit 6: Eigenvalues & Curve Fitting
    {
        "id": "19",
        "title": "Power Method for Dominant Eigenvalue",
        "category": "Eigenvalues \\& Curve Fitting",
        "chapter": "Eigenvalue Problems \\& Curve Fitting",
        "detailed_file": "19_power_method_detailed.py",
        "desc": "The Power Method is an iterative technique that computes the dominant eigenvalue (largest absolute magnitude) and its corresponding eigenvector for a square matrix $A$.",
        "formula": r"""\[
y_{k+1} = A x_k, \quad \lambda_{k+1} = \max(|y_{k+1}|), \quad x_{k+1} = \frac{y_{k+1}}{\lambda_{k+1}}
\]
\[
\text{Convergence Rate: } \left|\frac{\lambda_2}{\lambda_1}\right|^k \quad (\text{Requires } |\lambda_1| > |\lambda_2|)
\]"""
    },
    {
        "id": "20",
        "title": "Linear Curve Fitting (Least Squares)",
        "category": "Eigenvalues \\& Curve Fitting",
        "chapter": "Eigenvalue Problems \\& Curve Fitting",
        "detailed_file": "20_linear_fit_detailed.py",
        "desc": "Linear curve fitting finds the best-fit line $y = mx + c$ for a dataset of $n$ points by minimizing the sum of squared vertical residuals $\\sum (y_i - (mx_i + c))^2$.",
        "formula": r"""\[
\text{Normal Equations: } n c + m \sum x = \sum y, \quad c \sum x + m \sum x^2 = \sum x y
\]
\[
m = \frac{n \sum xy - \sum x \sum y}{n \sum x^2 - (\sum x)^2}, \quad c = \frac{\sum y - m \sum x}{n}
\]"""
    }
]

def run_script(path):
    res = subprocess.run(["python3", path], capture_output=True, text=True)
    return res.stdout.strip()

def build():
    print("[*] Generating LaTeX document...")
    tex_path = os.path.join(BUILD_DIR, "handbook.tex")
    
    with open(tex_path, "w", encoding="utf-8") as f:
        f.write(r"""\documentclass[10pt,a4paper]{report}

% --- Essential Packages ---
\usepackage[utf8]{inputenc}
\usepackage[margin=0.75in,headheight=14pt]{geometry}
\usepackage{amsmath,amssymb}
\usepackage{xcolor}
\usepackage{tcolorbox}
\usepackage{listings}
\usepackage{fancyhdr}
\usepackage{titlesec}
\usepackage{booktabs}
\usepackage{enumitem}
\usepackage{hyperref}
\usepackage{bookmark}

% --- Color Palette ---
\definecolor{primary}{HTML}{0F172A}       % Deep Slate 900
\definecolor{secondary}{HTML}{1E40AF}     % Cobalt 800
\definecolor{accentteal}{HTML}{0D9488}    % Teal 600
\definecolor{codebg}{HTML}{F8FAFC}        % Off-white editor tint
\definecolor{termbg}{HTML}{0F172A}        % Dark terminal background
\definecolor{termfg}{HTML}{38BDF8}        % Cyan/Mint terminal text
\definecolor{theorybg}{HTML}{F0FDF4}      % Light emerald tint
\definecolor{theoryframe}{HTML}{16A34A}   % Emerald border

% --- Syntax Highlighting Colors ---
\definecolor{pykeyword}{HTML}{7C3AED}     % Violet bold
\definecolor{pystring}{HTML}{047857}      % Emerald
\definecolor{pycomment}{HTML}{64748B}     % Slate italic
\definecolor{pynumber}{HTML}{C2410C}      % Orange/Coral
\definecolor{pybuiltin}{HTML}{2563EB}     % Blue bold

% --- Listings Definitions ---
\lstdefinestyle{python_detailed}{
    backgroundcolor=\color{codebg},
    basicstyle=\ttfamily\scriptsize\color{primary},
    keywordstyle=\color{pykeyword}\bfseries,
    commentstyle=\color{pycomment}\itshape,
    stringstyle=\color{pystring},
    numberstyle=\tiny\color{pycomment},
    numbers=left,
    numbersep=6pt,
    breaklines=true,
    breakatwhitespace=false,
    showstringspaces=false,
    keepspaces=true,
    tabsize=4,
    morekeywords={with,as,True,False,None,self,append,round,range,len,abs,float,int}
}

\lstdefinestyle{terminal_output}{
    backgroundcolor=\color{termbg},
    basicstyle=\ttfamily\tiny\color{termfg},
    breaklines=true,
    breakatwhitespace=false,
    showstringspaces=false,
    keepspaces=true,
    numbers=none
}

% --- Chapter & Section Heading Styling ---
\titleformat{\chapter}[display]
  {\normalfont\huge\bfseries\color{primary}}
  {\filleft\Huge\textbf{\color{secondary}Chapter \thechapter}}
  {1ex}
  {\titlerule[2pt]\vspace{1ex}}
  [\vspace{1ex}\titlerule]

\titleformat{\section}
  {\normalfont\Large\bfseries\color{secondary}}
  {\thesection}{1em}{}

% --- Page Header & Footer ---
\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{\small\textbf{\color{secondary}Numerical Computing in Python}}
\fancyhead[R]{\small\nouppercase{\color{pycomment}\leftmark}}
\fancyfoot[L]{\scriptsize\textbf{\color{secondary}Code by Anushka}}
\fancyfoot[R]{\small\thepage}
\renewcommand{\headrulewidth}{0.6pt}
\renewcommand{\footrulewidth}{0.4pt}

% --- Hyperlink Setup ---
\hypersetup{
    colorlinks=true,
    linkcolor=secondary,
    urlcolor=accentteal,
    pdftitle={Numerical Computing Python Complete Handbook},
    pdfauthor={Code by Anushka},
    pdfsubject={Numerical Analysis and Computing Methods in Python}
}

\begin{document}

% ==========================================
% COVER PAGE
% ==========================================
\begin{titlepage}
\begin{center}
\vspace*{1.5cm}

{\Huge\bfseries\color{primary} NUMERICAL ANALYSIS \& COMPUTING}\\[0.4cm]
{\LARGE\bfseries\color{secondary} IN PYTHON}\\[0.8cm]

\textcolor{accentteal}{\rule{0.8\textwidth}{2.5pt}}\\[0.8cm]

{\Large\color{primary} A Complete Practical Handbook: Theoretical Formulations, Step-by-Step Procedural Implementations \& Iteration Convergence Tables}\\[1.5cm]

\begin{tcolorbox}[colback=codebg,colframe=secondary,width=0.88\textwidth,arc=4mm,boxrule=1.5pt]
\begin{center}
\textbf{\large\color{secondary} 20 Core Numerical Methods Included}\\[0.3cm]
\small\color{primary}
$\bullet$ Roots of Non-Linear Equations \quad $\bullet$ Systems of Linear Equations \\
$\bullet$ Interpolation \& Polynomials \quad $\bullet$ Numerical Quadrature \\
$\bullet$ Ordinary Differential Equations \quad $\bullet$ Eigenvalue Problems \& Fitting\\[0.2cm]
\textit{Featuring Clean Python 3 Syntax, Pure Procedural Functions, and Formatted Iteration Tables}
\end{center}
\end{tcolorbox}

\vfill

{\LARGE\textbf{\color{secondary}Code by Anushka}}\\[0.3cm]
{\small Semester 5 Mathematics \& Numerical Computing Laboratory Reference}\\[0.3cm]
{\small\today}

\end{center}
\end{titlepage}

% ==========================================
% TABLE OF CONTENTS
% ==========================================
\tableofcontents
\newpage
""")

        # Group by chapter
        chapters = {}
        for m in METADATA:
            chap = m["chapter"]
            if chap not in chapters:
                chapters[chap] = []
            chapters[chap].append(m)

        for chap_title, methods in chapters.items():
            f.write(f"\\chapter{{{chap_title}}}\n\n")
            
            for m in methods:
                det_path = os.path.join(WORKSPACE, "detailed", m["detailed_file"])
                
                with open(det_path, "r", encoding="utf-8") as dfp:
                    det_code = dfp.read()
                    
                output_text = run_script(det_path)

                f.write(f"\\section{{{m['title']}}}\n")
                f.write(f"\\textbf{{Category:}} \\textcolor{{secondary}}{{{m['category']}}} \\quad | \\quad \\textbf{{Code by:}} \\textcolor{{secondary}}{{Anushka}} \\quad | \\quad \\textbf{{Source:}} \\texttt{{\\detokenize{{{m['detailed_file']}}}}}\n\n")
                
                f.write(f"{m['desc']}\n\n")
                
                # Math Card
                f.write(r"""\begin{tcolorbox}[colback=theorybg,colframe=theoryframe,title=\textbf{Mathematical Theory \& Formulation},boxrule=1pt,arc=2mm]""" + "\n")
                f.write(m["formula"] + "\n")
                f.write(r"""\end{tcolorbox}""" + "\n\n")

                # Detailed Code Card
                f.write(r"""\begin{tcolorbox}[colback=codebg,colframe=secondary,title=\textbf{Python Implementation (Step-by-Step Loops \& Pure Functions)},boxrule=1pt,arc=2mm]""" + "\n")
                f.write(r"""\begin{lstlisting}[style=python_detailed]""" + "\n")
                f.write(det_code + "\n")
                f.write(r"""\end{lstlisting}""" + "\n")
                f.write(r"""\end{tcolorbox}""" + "\n\n")

                # Output Card
                if output_text:
                    f.write(r"""\begin{tcolorbox}[colback=termbg,colframe=primary,title=\textbf{Program Execution Output \& Convergence Table},boxrule=1pt,arc=2mm]""" + "\n")
                    f.write(r"""\begin{lstlisting}[style=terminal_output]""" + "\n")
                    f.write(output_text + "\n")
                    f.write(r"""\end{lstlisting}""" + "\n")
                    f.write(r"""\end{tcolorbox}""" + "\n\n")

                f.write(r"\newpage" + "\n\n")

        # Summary Table at the end
        f.write(r"""\chapter{Master Summary \& Quick-Reference Guide}

\begin{tcolorbox}[colback=codebg,colframe=secondary,title=\textbf{Unit 1: Roots of Non-Linear Equations},boxrule=1.2pt,arc=2mm]
\begin{itemize}[leftmargin=*,itemsep=4pt]
\item \textbf{1. Bisection Method:} $c = (a+b)/2.0$. Halves bracket interval. Order: Linear ($\mathcal{O}(2^{-n})$). Always converges if $f(a)f(b) < 0$.
\item \textbf{2. Regula-Falsi (False Position):} $c = \frac{a f(b) - b f(a)}{f(b) - f(a)}$. Secant line $x$-intercept with guaranteed bracketing. Order: Superlinear to Linear.
\item \textbf{3. Newton-Raphson Method:} $x_{k+1} = x_k - \frac{f(x_k)}{f'(x_k)}$. Tangent line root approximation. Order: Quadratic ($p=2$).
\item \textbf{4. Secant Method:} $x_{k+1} = x_k - f(x_k)\frac{x_k - x_{k-1}}{f(x_k) - f(x_{k-1})}$. Finite-difference slope approximation. Order: $p \approx 1.618$.
\item \textbf{5. Fixed-Point Iteration:} $x_{k+1} = g(x_k)$. Converges linearly if $|g'(x)| < 1$ in neighborhood of the fixed point.
\end{itemize}
\end{tcolorbox}

\begin{tcolorbox}[colback=codebg,colframe=secondary,title=\textbf{Unit 2: Systems of Linear Algebraic Equations},boxrule=1.2pt,arc=2mm]
\begin{itemize}[leftmargin=*,itemsep=4pt]
\item \textbf{6. Gauss Elimination:} Converts $[A \mid b]$ to upper-triangular matrix, followed by back substitution. Operations: $\mathcal{O}(\frac{2}{3}n^3)$.
\item \textbf{7. Gauss-Jordan Elimination:} Direct reduction to reduced row echelon form $[I \mid x]$ eliminating back substitution. Operations: $\mathcal{O}(n^3)$.
\item \textbf{8. Gauss-Jacobi Iteration:} $x_i^{(k+1)} = \frac{1}{a_{ii}}(b_i - \sum_{j \neq i} a_{ij} x_j^{(k)})$. Requires strict diagonal dominance.
\item \textbf{9. Gauss-Seidel Iteration:} $x_i^{(k+1)} = \frac{1}{a_{ii}}(b_i - \sum_{j < i} a_{ij} x_j^{(k+1)} - \sum_{j > i} a_{ij} x_j^{(k)})$. Converges $\approx 2\times$ faster than Jacobi.
\end{itemize}
\end{tcolorbox}

\begin{tcolorbox}[colback=codebg,colframe=secondary,title=\textbf{Unit 3: Interpolation \& Polynomial Approximation},boxrule=1.2pt,arc=2mm]
\begin{itemize}[leftmargin=*,itemsep=4pt]
\item \textbf{10. Lagrange Interpolation:} $P(x) = \sum y_i \prod_{j \neq i} \frac{x - x_j}{x_i - x_j}$. Flexible formulation for arbitrary, unequally spaced nodes.
\item \textbf{11. Newton's Divided Difference:} $P(x) = f[x_0] + \sum_{k=1}^n f[x_0,\dots,x_k] \prod_{j=0}^{k-1} (x - x_j)$. Ideal for incrementally adding data points.
\item \textbf{12. Newton's Forward Difference:} $P(x) = y_0 + u \Delta y_0 + \frac{u(u-1)}{2!} \Delta^2 y_0 + \dots$. Specifically for equispaced points ($u = (x-x_0)/h$).
\end{itemize}
\end{tcolorbox}

\begin{tcolorbox}[colback=codebg,colframe=secondary,title=\textbf{Unit 4: Numerical Quadrature \& Integration},boxrule=1.2pt,arc=2mm]
\begin{itemize}[leftmargin=*,itemsep=4pt]
\item \textbf{13. Trapezoidal Rule:} $I \approx \frac{h}{2}[f(a) + 2\sum_{i=1}^{n-1} f(x_i) + f(b)]$. Linear piecewise approximation. Error: $\mathcal{O}(h^2)$.
\item \textbf{14. Simpson's 1/3 Rule:} $I \approx \frac{h}{3}[f(a) + f(b) + 4\sum_{\text{odd}} + 2\sum_{\text{even}}]$. Parabolic piecewise fits. Requires even $n$. Error: $\mathcal{O}(h^4)$.
\item \textbf{15. Simpson's 3/8 Rule:} $I \approx \frac{3h}{8}[f(a) + f(b) + 3\sum_{i \nmid 3} + 2\sum_{i \mid 3}]$. Cubic piecewise fits. Requires $n$ multiple of 3. Error: $\mathcal{O}(h^4)$.
\end{itemize}
\end{tcolorbox}

\begin{tcolorbox}[colback=codebg,colframe=secondary,title=\textbf{Unit 5 \& 6: Differential Equations, Eigenvalues \& Curve Fitting},boxrule=1.2pt,arc=2mm]
\begin{itemize}[leftmargin=*,itemsep=4pt]
\item \textbf{16. Euler's Method:} $y_{n+1} = y_n + h f(x_n, y_n)$. Single-step explicit tangent method. Order: First-order $\mathcal{O}(h)$.
\item \textbf{17. Modified Euler (Heun's):} Predictor-corrector scheme. Predicts $\tilde{y}_{n+1}$, corrects using average slope. Order: Second-order $\mathcal{O}(h^2)$.
\item \textbf{18. Runge-Kutta 4 (RK4):} Four weighted intermediate slopes per step. Gold standard for initial value ODEs. Order: Fourth-order $\mathcal{O}(h^4)$.
\item \textbf{19. Power Method:} $y_{k+1} = A x_k, \ \lambda_{k+1} = \max(|y_{k+1}|), \ x_{k+1} = y_{k+1} / \lambda_{k+1}$. Iteratively converges to dominant eigenvalue.
\item \textbf{20. Linear Curve Fitting:} Minimizes $\sum (y_i - (m x_i + c))^2$ to determine optimal slope $m$ and intercept $c$ for best-fit straight line.
\end{itemize}
\end{tcolorbox}

\end{document}
""")
    
    print("[*] Compiling LaTeX with pdflatex (Pass 1)...")
    res1 = subprocess.run(["pdflatex", "-interaction=nonstopmode", "handbook.tex"], 
                          cwd=BUILD_DIR, capture_output=True, text=True)
    if res1.returncode != 0:
        print("[-] Error in Pass 1:")
        print(res1.stdout[-1500:])
        return False
        
    print("[*] Compiling LaTeX with pdflatex (Pass 2 for TOC & Bookmarks)...")
    res2 = subprocess.run(["pdflatex", "-interaction=nonstopmode", "handbook.tex"], 
                          cwd=BUILD_DIR, capture_output=True, text=True)
    if res2.returncode != 0:
        print("[-] Error in Pass 2:")
        print(res2.stdout[-1500:])
        return False
        
    built_pdf = os.path.join(BUILD_DIR, "handbook.pdf")
    subprocess.run(["cp", built_pdf, OUTPUT_PDF])
    alt_pdf = os.path.join(WORKSPACE, "numerical_analysis_code_handbook.pdf")
    subprocess.run(["cp", built_pdf, alt_pdf])
    print(f"[+] Successfully created PDF at: {OUTPUT_PDF} and {alt_pdf}")
    return True

if __name__ == "__main__":
    build()
